// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vou.Services.VoucherAPI.Data;

#nullable disable

namespace Vou.Services.VoucherAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240908122545_CreateVoucherTable")]
    partial class CreateVoucherTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vou.Services.VoucherAPI.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voucher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Voucher 1",
                            Description = "Voucher vip",
                            ExpireDate = new DateTime(2024, 9, 15, 19, 25, 44, 987, DateTimeKind.Local).AddTicks(7618),
                            Img = "123123",
                            QRCode = "123213213",
                            State = true,
                            Value = 10
                        },
                        new
                        {
                            Id = 2,
                            Code = "Voucher 2",
                            Description = "Voucher vip",
                            ExpireDate = new DateTime(2024, 9, 15, 19, 25, 44, 987, DateTimeKind.Local).AddTicks(7670),
                            Img = "123123",
                            QRCode = "123213213",
                            State = true,
                            Value = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
